config/routes.rb
Rails.application.routes.draw do

  get 'pages/inscription'

  get 'pages/accueil'

  get 'pages/sports'

  get 'pages/infos'

  get 'pages/classement'

  get 'pages/account'

  get 'pages/bet'

  get 'pages/friends'

  root 'pages#index'

end

app/models/MySqlCon.rb
# Include Ruby Gem libraries.
require 'rubygems'
require 'mysql2'

 
begin
  # Create new database connection.
  client = Mysql2::Client.new(:host => "localhost", :username => "root", :password => "root")
  # Print connected message.
  puts "Connected to the MySQL database server."
  joueurs = joueur.find(0)
  puts joueurs


rescue Mysql::Error => e
  # Print the error.
  puts "ERROR #{e.errno} (#{e.sqlstate}): #{e.error}"
  puts "Can't connect to the MySQL database specified."
  # Signal an error.
  exit 1
ensure
  # Close the connection when it is open.
end

app/models/User.rb
class User
  attr_accessor :name, :surname, :email

  def initialize(attributes = {})
    @name  = attributes[:name]
    @email = attributes[:email]
    @surname=attributes[:surname]
  end

  def formatted_email
    "#{@name} <#{@email}>"
  end
end

app/models/equipe.rb
class Equipe < ActiveRecord::Base
  belongs_to :id_sport
end

app/models/joueur.rb
class Joueur < ActiveRecord::Base
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :id_sport
end

app/models/pari.rb
class Pari < ActiveRecord::Base
  belongs_to :id_match
  belongs_to :id_user
end

app/models/sport.rb
class Sport < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def inex
        
    end
    
    
  def sports
      @title = "| Sport"
      $lstParis = ["Bordeaux - Montpellier", "EUH"]
      $lstLigue = ["Ligue 1", "Ligue 2"]
  end

  def infos
      @title = "| Infos"
  end

  def classement
      @title = "| Classement"
  end

  def account
  	@title = "| Account"
  end

  def bet
  	@title = "| Paris"
  end

  def friends
  	@title = "| Friends"
  end
def inscription
    @user = User.new
    @title = "Sign up"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BForSport <%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    
    <!-- Mobile Internet Explorer ClearType Technology -->
    <!--[if IEMobile]>  <meta http-equiv="cleartype" content="on">  <![endif]-->
    
    <%= stylesheet_link_tag "main.css" %>
    
    <!-- Google Font -->
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900" %>
    
    <!-- Fav Icon -->
    <link rel="shortcut icon"  type="image/jpeg" href="/assets/BforSport.ico">
    
    <!-- Modernizr -->
    <script src="/assets/modernizr.js"></script>
    
    
    </head>
<body>

<%= yield %>

    <!-- Js -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> <!-- jQuery Core -->
<script src="/assets/bootstrap.min.js"></script> <!-- Bootstrap -->
<script src="/assets/supersized.3.2.7.min.js"></script> <!-- Slider -->
<script src="/assets/waypoints.js"></script> <!-- WayPoints -->
<script src="/assets/waypoints-sticky.js"></script> <!-- Waypoints for Header -->
<script src="/assets/jquery.isotope.js"></script> <!-- Isotope Filter -->
<script src="/assets/jquery.fancybox.pack.js"></script> <!-- Fancybox -->
<script src="/assets/jquery.fancybox-media.js"></script> <!-- Fancybox for Media -->
<script src="/assets/jquery.tweet.js"></script> <!-- Tweet -->
<script src="/assets/plugins.js"></script> <!-- Contains: jPreloader, jQuery Easing, jQuery ScrollTo, jQuery One Page Navi -->
<script src="/assets/main.js"></script> <!-- Default JS -->
<!-- End Js -->
</body>
</html>

app/views/pages/Inscription.erb
<!-- Inscription Form -->
<h2>Sign up</h2>
<div class="row">
<% form_for(@user) do |f| %>
  <div class="span9">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="contact-email">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="contact-message">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="contact-message">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
    

<% end %>
  </div>
    

app/views/pages/account.html.erb
<!-- This section is for Splash Screen -->
<div class="ole">
<section id="jSplash">
	<div id="circle"></div>
</section>
</div>
<!-- End of Splash Screen -->

<!-- Header -->
<header>
    <div class="sticky-nav">
    	<a id="mobile-nav" class="menu-nav" href="#menu-nav"></a>
        
        <div id="logo">
        	<a id="goUp" href="#home-slider" title="Brushed | Responsive One Page Template">Brushed Template</a>
        </div>
        
        <nav id="menu">
        	<ul id="menu-nav">
            	<li><%= link_to "Accueil", root_path, :class => "external" %></a></li>
                <li class="current"><%= link_to "Sports", pages_sports_path, :class => "external" %></li>
                <li><a href="#about">Classement</a></li>
                <li> Se déconnecter </li>
            </ul>
        </nav>
        
    </div>
</header>
<!-- End Header -->

<div id="shortcodes" class="page">
	<div class="container">
    
    	<!-- Title Page -->
        <div class="row">
            <div class="span12">
                <div class="title-page">
                    <h2 class="title">Mon compte</h2>
                    <!-- <h3 class="title-description">Useful and Indispensable.</h3> -->
                </div>
            </div>
        </div>
        <!-- End Title Page -->
        
        <!-- Informations de compte -->

        <div class="row">
        	<div class="span12">
        	<h3 class="title-description"> Informations de compte</h3>
        		<li> Nom d'utilisateur : </li>
        		<li> Adresse email : </li>
        		<li> Classement actuel : </li>
        	</div>
        </div>



        <div class="row">
        	<div class="span12">
            	<hr>
            </div>
        </div>

        <!-- Historique -->

        <div class="row">
        	<div class="span12">
        	<h3 class="title-description"> Historique des paris</h3>
        		<li> Nombre de paris au total : </li>
        		<li> Nombre de paris réussie : </li>
        	</div>
        </div>
        
        
        <div class="row">
        	<div class="span12">
            	<hr>
            </div>	
        </div>
        
        <!-- Administration du compte-->

        <div class="row">
        	<div class="span12">
        	<h3 class="title-description"> Admninistration du compte</h3>
        	<h4 class="description"> Changer de mot de passe </h4>
        		<li> Ancien mot de passe : </li>
        		<li> Nouveau mot de passe : </li>
        		<li> Retapper le mot de passe : </li>
        		<a class="delete-account" href="#">Supprimer le compte</a>
        	</div>
        </div>
        
        <div class="row">
        	<div class="span12">
            	<hr>
            </div>	
        </div>
        
        
        <div class="row">
        	<div class="span12">
            	<hr>
            </div>	
        </div>
        
        
        <div class="row">
        	<div class="span12">
            	<hr>
            </div>	
        </div>
        
    </div>
</div>
<!-- End Shortcodes Section -->

<!-- Footer -->
<footer>
	<p class="credits">&copy;2013 Brushed. <a href="http://themes.alessioatzeni.com/html/brushed/" title="Brushed | Responsive One Page Template">Brushed Template</a> by <a href="http://www.alessioatzeni.com/" title="Alessio Atzeni | Web Designer &amp; Front-end Developer">Alessio Atzeni</a></p>
</footer>
<!-- End Footer -->

<!-- Back To Top -->
<a id="back-to-top" href="#">
	<i class="font-icon-arrow-simple-up"></i>
</a>
<!-- End Back to Top -->

app/views/pages/accueil.html.erb
<h1>Pages#accueil</h1>
<p>Find me in app/views/pages/accueil.html.erb</p>

app/views/pages/classement.html.erb
<h1>Pages#classement</h1>
<p>Find me in app/views/pages/classement.html.erb</p>

app/views/pages/friends.html.erb
<!-- This section is for Splash Screen -->
<div class="ole">
<section id="jSplash">
	<div id="circle"></div>
</section>
</div>
<!-- End of Splash Screen -->

<!-- Header -->
<header>
    <div class="sticky-nav">
    	<a id="mobile-nav" class="menu-nav" href="#menu-nav"></a>
        
        <div id="logo">
        	<a id="goUp" href="#home-slider" title="Brushed | Responsive One Page Template">Brushed Template</a>
        </div>
        
        <nav id="menu">
        	<ul id="menu-nav">
            	<li><%= link_to "Accueil", root_path, :class => "external" %></a></li>
                <li><%= link_to "Classement", pages_classement_path, :class => "external" %></li>
                <li><%= link_to "Mon compte", pages_account_path, :class => "external" %></li>
                <li> Se déconnecter </li>
            </ul>
        </nav>
        
    </div>
</header>
<!-- End Header -->

<div id="shortcodes" class="page">
	<div class="container">
    
    	<!-- Title Page -->
        <div class="row">
            <div class="span12">
                <div class="title-page">
                    <h2 class="title">Mes amis</h2>
                    <!-- <h3 class="title-description">Useful and Indispensable.</h3> -->
                </div>
            </div>
        </div>
        <!-- End Title Page -->
        
        <!-- Ajouter un ami -->

        <div class="row">
        	<div class="span12">
        	<h3 class="title-description"> Ajouter un nouvel ami</h3>
        		<li> Par son nom d'utilisateur : </li>
        		<li> Par son adresse email : </li>
                <a class="add-friends" href="#">Ajouter un ami</a>
        	</div>
        </div>



        <div class="row">
        	<div class="span12">
            	<hr>
            </div>
        </div>

        <!-- Gestion des amis -->

        <div class="row">
        	<div class="span12">
        	<h3 class="title-description"> Top 3 des amis</h3>
        		<li> Numéro 1 : </li>
        		<li> Numéro 2 : </li>
                <li> Numéro 3 : </li>
                <br>
                <h3 class="title description"> Rechercher un ami</h3>
                <li> Nom d'utilisateur : </li>
        	</div>
        </div>

        
        
        <div class="row">
        	<div class="span12">
            	<hr>
            </div>	
        </div>
        
        
       
        
    </div>
</div>
<!-- End Shortcodes Section -->

<!-- Footer -->
<footer>
	<p class="credits">&copy;2013 Brushed. <a href="http://themes.alessioatzeni.com/html/brushed/" title="Brushed | Responsive One Page Template">Brushed Template</a> by <a href="http://www.alessioatzeni.com/" title="Alessio Atzeni | Web Designer &amp; Front-end Developer">Alessio Atzeni</a></p>
</footer>
<!-- End Footer -->

<!-- Back To Top -->
<a id="back-to-top" href="#">
	<i class="font-icon-arrow-simple-up"></i>
</a>
<!-- End Back to Top -->

app/views/pages/index.html.erb
<!-- This section is for Splash Screen -->
<div class="ole">
<section id="jSplash">
	<div id="circle"></div>
</section>
</div>
<!-- End of Splash Screen -->

<!-- Homepage Slider -->
<div id="home-slider">	
    <div class="overlay"></div>

    <div class="slider-text">
    	<div id="slidecaption"></div>
    </div>   
	
	<div class="control-nav">
        <a id="prevslide" class="load-item"><i class="font-icon-arrow-simple-left"></i></a>
        <a id="nextslide" class="load-item"><i class="font-icon-arrow-simple-right"></i></a>
        <ul id="slide-list"></ul>
        
        <a id="nextsection" href="#work"><i class="font-icon-arrow-simple-down"></i></a>
    </div>
</div>
<!-- End Homepage Slider -->
 
<!-- Header -->
<header>
    <div class="sticky-nav">
    	<a id="mobile-nav" class="menu-nav" href="#menu-nav"></a>
        
        <div id="logo">
        	<a id="goUp" href="#home-slider" title="B For Sport">BForSport</a>
        </div>
        
        <nav id="menu">
        	<ul id="menu-nav">
            	<li class="current"><a href="#home-slider">Accueil</a></li>
                <li><%= link_to "Sports", pages_sports_path, :class => "external" %></li>
                <li><%= link_to "Mon compte", pages_account_path, :class => "external" %></li>
                <li><%= link_to "Classement", pages_classement_path, :class => "external" %></li>
                <li><%= link_to "Paris", pages_bet_path, :class => "external" %></li>
                <li><%= link_to "Amis", pages_friends_path, :class => "external" %></li>
                 <li><%= link_to "Inscription", pages_inscription_path,  :class => "external" %></li>
                <li><a href="#about">A Propos</a></li>
            </ul>
        </nav>
        
    </div>
</header>
<!-- End Header -->

<!-- Our Work Section -->
<div id="work" class="page">
	<div class="container">
    	<!-- Title Page -->
        <div class="row">
            <div class="span12">
                <div class="title-page">
                    <h2 class="title">Les actualités</h2>
                    <h3 class="title-description">Retrouvez les dernières actualités par sport</h3>
                </div>
            </div>
        </div>
        <!-- End Title Page -->
        
        <!-- Portfolio Projects -->
        <div class="row">
        	<div class="span3">
            	<!-- Filter -->
                <nav id="options" class="work-nav">
                    <ul id="filters" class="option-set" data-option-key="filter">
                    	<li class="type-work">Catégories</li>
                        <li><a href="#filter" data-option-value="*" class="selected">Tous</a></li>
                        <li><a href="#filter" data-option-value=".design">Football</a></li>
                        <li><a href="#filter" data-option-value=".photography">Tennis</a></li>
                        <li><a href="#filter" data-option-value=".video">Basketball</a></li>
                    </ul>
                </nav>
                <!-- End Filter -->
            </div>
            
            <div class="span9">
            	<div class="row">
                	<section id="projects">
                    	<ul id="thumbs">
                        
                            
							<li>
                            <h2 class="title">Le PSG en route pour le triplé</h2>
                            <h3 class="title-description">Après avoir remporté la coupe de la ligue ainsi que le championnat, le PSG n'a plus qu'a se concentrer sur la coupe de France contre Auxerre qui se jouera le samedi 30 mai au stade de France. Cette finale sera très disputés puisque cela permettrait à Auxerre d'accèder à l'europa league et de finir la saison avec un trophée et quand au PSG cela lui permettrait de réaliser un triplé.</h3>
                            <%= image_tag("Psg.jpg") %>
                            </li>
                        </ul>
                    </section>
                    
            	</div>
            </div>
        </div>
        <!-- End Portfolio Projects -->
    </div>
</div>
<!-- End Our Work Section -->

<!-- About Section -->
<div id="about" class="page-alternate">
<div class="container">
    <!-- Title Page -->
    <div class="row">
        <div class="span12">
            <div class="title-page">
                <h2 class="title">A Propos</h2>
                <h3 class="title-description">Learn About our Team &amp; Culture.</h3>
            </div>
        </div>
    </div>
    <!-- End Title Page -->
    
    <!-- People -->
    <div class="row">
    	
        <!-- Start Profile -->
    	<div class="span4 profile">
        	<div class="image-wrap">
                <div class="hover-wrap">
                    <span class="overlay-img"></span>
                    <span class="overlay-text-thumb">Chef d'équipe</span>
                </div>
                <%= image_tag("jimmy.jpg") %>
            </div>
            <h3 class="profile-name">Jimmy Farvault</h3>
            <p class="profile-description">Un pur Beau gosse!</p>
            	
            <div class="social">
            	<ul class="social-icons">
                	<li><a href="https://fr.linkedin.com/in/jfarvault"><i class="font-icon-social-linkedin"></i></a></li>
                    <li><a href="https://twitter.com/jiimmyster"><i class="font-icon-social-twitter"></i></a></li>
                    <li><a href="https://plus.google.com/+JimmyFARVAULT1/posts"><i class="font-icon-social-google-plus"></i></a></li>
                    <li><a href="mailto:contact@jimmyf.fr"><i class="font-icon-social-email"></i></a></li>
                </ul>
            </div>
        </div>
        <!-- End Profile -->
        
        <!-- Start Profile -->
    	<div class="span4 profile">
        	<div class="image-wrap">
                <div class="hover-wrap">
                    <span class="overlay-img"></span>
                    <span class="overlay-text-thumb">Back Development</span>
                </div>
                <%= image_tag("alexandre.jpg") %>
            </div>
            <h3 class="profile-name">Alexandre Plaitant</h3>
            <p class="profile-description">Toujours à l'écoute et disponible. Il est un point clé dans la vie d'une équipe!</p>
            	
            <div class="social">
            	<ul class="social-icons">
                	<li><a href="https://twitter.com/Dranaxele"><i class="font-icon-social-twitter"></i></a></li>
                    <li><a href="https://www.facebook.com/alexandreplaitant"><i class="font-icon-social-facebook"></i></a></li>
                    <li><a href="https://plus.google.com/u/0/102835950596744372033/posts"><i class="font-icon-social-google-plus"></i></a></li>
                </ul>
            </div>
        </div>
        <!-- End Profile -->
        
        <!-- Start Profile -->
    	<div class="span4 profile">
        	<div class="image-wrap">
                <div class="hover-wrap">
                    <span class="overlay-img"></span>
                    <span class="overlay-text-thumb">Responsable Sport</span>
                </div>
                <%= image_tag("yoann.jpg") %>
            </div>
            <h3 class="profile-name">Yoann Murat</h3>
            <p class="profile-description">Seulement disponible entre deux parties de LOL, il pourra vous conseiller sur n'importe quelle choix</p>
            	
            <div class="social">
            	<ul class="social-icons">
                	<li><a href="https://www.facebook.com/yoann.murat.1?fref=ts"><i class="font-icon-social-facebook"></i></a></li>
                	<li><a href="https://fr.linkedin.com/pub/yoann-murat/a0/524/635"><i class="font-icon-social-linkedin"></i></a></li>
                </ul>
            </div>
        </div>
        <!-- End Profile -->
        
        <!-- Start Profile -->
    	<div class="span4 profile">
        	<div class="image-wrap">
                <div class="hover-wrap">
                    <span class="overlay-img"></span>
                    <span class="overlay-text-thumb">Responsable Design</span>
                </div>
                <%= image_tag("marvin.jpg") %>
            </div>
            <h3 class="profile-name">Marvin Fischer</h3>
            <p class="profile-description">Toujours là pour vous servir !! Quel homme exceptionnel .... </p>
            	
            <div class="social">
            	<ul class="social-icons">
                    <li><a href="https://www.facebook.com/profile.php?id=100008449816128&fref=ts"><i class="font-icon-social-facebook"></i></a></li>
                </ul>
            </div>
        </div>
        <!-- End Profile -->
        
        <!-- Start Profile -->
    	<div class="span4 profile">
        	<div class="image-wrap">
                <div class="hover-wrap">
                    <span class="overlay-img"></span>
                    <span class="overlay-text-thumb">Responsable CDCF</span>
                </div>
                <%= image_tag("benoit.jpg") %>
            </div>
            <h3 class="profile-name">Benoit Bento</h3>
            <p class="profile-description">Un coup de pompe?! Faites appel à lui pour regonfler les troupes!</p>
            	
            <div class="social">
            	<ul class="social-icons">
                	<li><a href="https://www.facebook.com/kamel.bento?fref=ts"><i class="font-icon-social-facebook"></i></a></li>
                </ul>
            </div>
        </div>
        <!-- End Profile -->
        
    </div>
    <!-- End People -->
</div>
</div>
<!-- End About Section -->

<!-- Footer -->
<footer>
	<p class="credits">&copy;2013 Brushed. <a href="http://themes.alessioatzeni.com/html/brushed/" title="Brushed | Responsive One Page Template">Brushed Template</a> by <a href="http://www.alessioatzeni.com/" title="Alessio Atzeni | Web Designer &amp; Front-end Developer">Alessio Atzeni</a></p>
</footer>
<!-- End Footer -->

<!-- Back To Top -->
<a id="back-to-top" href="#">
	<i class="font-icon-arrow-simple-up"></i>
</a>
<!-- End Back to Top -->

app/views/pages/infos.html.erb
<h1>Pages#infos</h1>
<p>Find me in app/views/pages/infos.html.erb</p>

app/views/pages/inscription.erb
<!-- Inscription Form -->
<h2>Sign up</h2>
<div class="row">
<% form_for(@user) do |f| %>
  <div class="span9">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="contact-email">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="contact-message">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="contact-message">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
    

<% end %>
  </div>
    

app/views/pages/sports.html.erb
<!-- This section is for Splash Screen -->
<div class="ole">
<section id="jSplash">
	<div id="circle"></div>
</section>
</div>
<!-- End of Splash Screen -->

<!-- Header -->
<header>
    <div class="sticky-nav">
    	<a id="mobile-nav" class="menu-nav" href="#menu-nav"></a>
        
        <div id="logo">
        	<a id="goUp" href="#home-slider" title="Brushed | Responsive One Page Template">Brushed Template</a>
        </div>
        
        <nav id="menu">
        	<ul id="menu-nav">
            	<li><%= link_to "Accueil", root_path, :class => "external" %></a></li>
                <li class="current"><%= link_to "Sports", pages_sports_path, :class => "external" %></li>
                <li><a href="#about">Classement</a></li>
                <li><a href="#contact">Infos</a></li>
				<li><a href="shortcodes.html" class="external">Shortcodes</a></li>
            </ul>
        </nav>
        
    </div>
</header>
<!-- End Header -->

<div id="shortcodes" class="page">
	<div class="container">
    
    	<!-- Title Page -->
        <div class="row">
            <div class="span12">
                <div class="title-page">
                    <h2 class="title">Un titre de page?</h2>
                    <h3 class="title-description">Bienvenue sur la page pour faire vos paris sur le sport qui vous plait</h3>
                </div>
            </div>
        </div>
        <!-- Start Alerts/Tabs Section -->
        <div class="row">
        	         
            <!-- Start Tabs -->
            <div class="span12">
            	<h3 class="spec">Les Paris</h3>
                
            	<div class="tabbable">
                
                    <ul class="nav nav-tabs" id="myTab">
                        <li class="active"><a href="#tab1" data-toggle="tab">Football</a></li>
                        <li><a href="#tab2" data-toggle="tab">Tennis</a></li>
                        <li><a href="#tab3" data-toggle="tab">ETC...</a></li>
                    </ul>
                 
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1">
                            <div class="span5">
            	               <!-- Filter -->
                                <nav id="options" class="work-nav">
                                    <ul id="filters" class="option-set" data-option-key="filter">
                                        <li class="type-work">Championnat</li>
                                        <% $lstLigue.each do |ligue| %>
                    	               <li><a href="#filter" data-option-value=".ligue1" class="selected"><%= ligue %></a></li>
                                        <% end %>
                                    </ul>
                                    <div class="span9">
                                    	<div class="row">
                                        	<section id="Ligue 1">
                                            	<ul id="thumbs">
                                                    <% $lstParis.each do |pari| %>
			                     				<!-- Item Project and Filter Name -->
                                                	<li class="item-thumbs span3 design">
                                                    	<!-- Fancybox - Gallery Enabled - Title - Full Image -->
                                                    	<a class="hover-wrap fancybox" data-fancybox-group="gallery" title=<%= pari %> href="/assets/foot.jpg">
                                                        	<span class="overlay-img"></span>
                                                            <span class="overlay-img-thumb font-icon-plus"></span>
                                                        </a>
                                                        <!-- Thumb Image and Description -->
<!--                                                        <%= image_tag("image-01.jpg") %>-->
                                                        <h2><%= pari %></h2>
                                                    </li>
                                                	<!-- End Item Project -->
                                                    <% end %>
                                                    
                                                </ul>
                                            </section>
                                            
                                    	</div>
                                    </div>
                                </nav>
                                <!-- End Filter -->
                            </div>
                        </div>
                        <div class="tab-pane fade in" id="tab2">
                            Aliquam volutpat arcu et nibh mollis eleifend pharetra lorem scelerisque. Donec vel enim purus, id viverra neque. Cras in velit ante, eget pellentesque sem. Duis tincidunt erat quam. Etiam placerat sapien elit.                            
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas neque diam, luctus at laoreet in, auctor ut tellus. Etiam enim lacus, ornare et tempor, rhoncus rhoncus sem.
                        </div>
                        <div class="tab-pane fade in" id="tab3">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas neque diam, luctus at laoreet in, auctor ut tellus. Etiam enim lacus, ornare et tempor, rhoncus rhoncus sem.
                            Aliquam volutpat arcu et nibh mollis eleifend pharetra lorem scelerisque. Donec vel enim purus, id viverra neque. Cras in velit ante, eget pellentesque sem. Duis tincidunt erat quam. Etiam placerat sapien elit.    
                        </div>
                    </div>
                            
				</div>
            </div>
            <!-- End Tabs -->
            
        </div>
        <!-- End Alerts/Tabs Section -->
        
        
        
    </div>
</div>
<!-- End Shortcodes Section -->

<!-- Footer -->
<footer>
	<p class="credits">&copy;2013 Brushed. <a href="http://themes.alessioatzeni.com/html/brushed/" title="Brushed | Responsive One Page Template">Brushed Template</a> by <a href="http://www.alessioatzeni.com/" title="Alessio Atzeni | Web Designer &amp; Front-end Developer">Alessio Atzeni</a></p>
</footer>
<!-- End Footer -->

<!-- Back To Top -->
<a id="back-to-top" href="#">
	<i class="font-icon-arrow-simple-up"></i>
</a>
<!-- End Back to Top -->